- name: Block password
  block:
    - name: Launch JBT for password change
      uri:
        url: "{{ tower_url }}/api/v2/workflow_job_templates/{{ post_install_jtl_password_management.json.results[0].id }}/launch/"
        user: "{{ tower_username }}"
        password: "{{ tower_password }}"
        force_basic_auth: yes
        method: POST
        body_format: json
        return_content : yes
        status_code: [201]
        body: '{"extra_vars":{"change_mdp_user_to_update":"{{ item }}","use_case_report_email":"{{ use_case_report_email }}"},"limit":"{{ post_install_hostname }}"}'
      register: post_install_jtl_password_management_launch
      delegate_to: localhost

    - name: Wait for job completion
      uri:
        url: "{{ tower_url }}/api/v2/workflow_jobs/{{ post_install_jtl_password_management_launch.json.workflow_job }}/"
        user: "{{ tower_username }}"
        password: "{{ tower_password }}"
        force_basic_auth: yes
        method: GET
        status_code: [200]
      register: post_install_jtl_password_management_job
      until: post_install_jtl_password_management_job.json.finished is search("-")
      retries: 60
      delay: 10
      delegate_to: localhost

    - name: Check job status
      fail:
        msg: "Password change for {{ item }} failed"
      when: post_install_jtl_password_management_job.json.status in 'failed' 'error' 'canceled'

    - name: Set passwords_changes informations
      set_fact:
        ae337: "{{ ae337 | combine({'passwords_changes': ae337.passwords_changes + [{'password':item, 'changed':'True' }]}) }}"	

  rescue:
    - name: Set passwords_changes informations
      set_fact:
        ae337: "{{ ae337 | combine({'passwords_changes': ae337.passwords_changes + [{'password':item, 'changed':'False' }]}) }}"	

    - name: Set status exec on server KO
      set_fact:
        ae337: "{{ ae337 | combine({'STATUS_EXEC': 'KO'}) }}"	