- name: Set password if expired
  delegate_to: localhost
  expect:
    command: ssh {{ ansible_ssh_common_args }} {{ ansible_user }}@{{ inventory_hostname }}
    timeout: 10
    responses:
      "password:":
        - "{{ ansible_password }}"
        - "{{ ansible_password }}"
        - "TeMP@ssw0rd!"
        - "TeMP@ssw0rd!"
      "\\~\\]\\$": exit
  register: change_pass_status

- name: Set password if expired
  delegate_to: localhost
  expect:
    command: ssh -t {{ ansible_ssh_common_args }} {{ ansible_user }}@{{ inventory_hostname }} passwd
    timeout: 10
    responses:
      "password:":
        - "TeMP@ssw0rd!"
        - "TeMP@ssw0rd!"
        - "{{ ansible_password }}"
        - "{{ ansible_password }}"
      "\\~\\]\\$": exit
  register: change_pass_status