- name: Block exploitation scripts
  block: 
    - name: Get Job Templates ID
      uri:
        url: "{{ tower_url }}/api/v2/job_templates/?name={{ post_install_exploitation_jtl_name }}"
        user: "{{ tower_username }}"
        password: "{{ tower_password }}"
        force_basic_auth: yes
        method: GET
        status_code: [200]
      register: post_install_jtl_exploitation_management
      delegate_to: localhost

    - name: Launch JBT for exploitation script deployment
      uri:
        url: "{{ tower_url }}/api/v2/job_templates/{{ post_install_jtl_exploitation_management.json.results[0].id }}/launch/"
        user: "{{ tower_username }}"
        password: "{{ tower_password }}"
        force_basic_auth: yes
        method: POST
        body_format: json
        return_content : yes
        status_code: [201]
        body: '{"extra_vars":{"use_case_report_email":"{{ use_case_report_email }}"},"limit":"{{ post_install_hostname }}"}'
      register: post_install_jtl_exploitation_management_launch
      delegate_to: localhost

    - name: Wait for job completion
      uri:
        url: "{{ tower_url }}/api/v2/jobs/{{ post_install_jtl_exploitation_management_launch.json.job }}/"
        user: "{{ tower_username }}"
        password: "{{ tower_password }}"
        force_basic_auth: yes
        method: GET
        status_code: [200]
      register: post_install_jtl_exploitation_management_job
      until: post_install_jtl_exploitation_management_job.json.finished is search("-")
      retries: 60
      delay: 10
      delegate_to: localhost

    - name: Check job status
      fail:
        msg: "Deployment of exploitation scripts failed"
      when: post_install_jtl_exploitation_management_job.json.status|lower in 'failed' 'error' 'canceled'

    - name: Set exploitation scripts OK
      set_fact:
        ae337: "{{ ae337 | combine({'exploitation_scripts': 'Deployed'}) }}"	

  rescue:
    - name: Set exploitation scripts KO
      set_fact:
        ae337: "{{ ae337 | combine({'exploitation_scripts': 'Not deployed'}) }}"	

    - name: Set status exec on server KO
      set_fact:
        ae337: "{{ ae337 | combine({'STATUS_EXEC': 'KO'}) }}"	